[package]
name = "m-scripts"
version = "0.1.0"
description = "Martin's Scripts"
authors = ["Martin Liu <hflhmartin@gmail.com>"]
edition = "2018"

[[bin]]
name = "m"
path = "src/main.rs"

[dependencies]
clap = { version = "4.1.7", features = ["derive"] }
